package org.firstinspires.ftc.teamcode.OpMode.StateMachine;

public enum GamepadButtons {
  GAMEPAD_1_A, GAMEPAD_1_B, GAMEPAD_1_X, GAMEPAD_1_Y,
  GAMEPAD_1_RT, GAMEPAD_1_LT, GAMEPAD_1_RB, GAMEPAD_1_LB,
  GAMEPAD_1_START,
  GAMEPAD_1_DPAD_LEFT, GAMEPAD_1_DPAD_RIGHT, GAMEPAD_1_DPAD_UP, GAMEPAD_1_DPAD_DOWN,
  GAMEPAD_1_LSX, GAMEPAD_1_LSY, GAMEPAD_1_RSX, GAMEPAD_1_RSY,

  GAMEPAD_2_A, GAMEPAD_2_B, GAMEPAD_2_X, GAMEPAD_2_Y,
  GAMEPAD_2_RT, GAMEPAD_2_LT, GAMEPAD_2_RB, GAMEPAD_2_LB,
  GAMEPAD_2_START,
  GAMEPAD_2_DPAD_LEFT, GAMEPAD_2_DPAD_RIGHT, GAMEPAD_2_DPAD_UP, GAMEPAD_2_DPAD_DOWN,
  GAMEPAD_2_LSX, GAMEPAD_2_LSY, GAMEPAD_2_RSX, GAMEPAD_2_RSY

}
